# Generated by Django 2.0.4 on 2018-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username_default', max_length=32),
            preserve_default=False,
        ),
    ]
