# Generated by Django 2.0.4 on 2018-04-24 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_billitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
